version: '3.3'

services:
  redis:
    image: redis:6.2-alpine
    restart: unless-stopped
  web:
    image: jlucasamorim/salz-staging:latest
    ports:
      - "8080:8080"
    restart: always
    environment:
      REDIS_URL: redis://redis:6379
      NODE_ENV: production
      PORT: 8080
    links:
      - redis
