version: '3.3'

services:
  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    restart: unless-stopped
  web:
    image: jlucasamorim/salz-staging:latest
    ports:
      - "8080:8080"
    restart: always
    environment:
      REDIS_URL: redis://redis:6379
      NODE_ENV: production
      PORT: 8080
    links:
      - redis
volumes:
  redis:
